project_id = "azuqquiicdtmgkyeseub"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54333

[functions.whatsapp-webhook-receiver]
verify_jwt = false

[functions.whatsapp-message-sender]
verify_jwt = true