[build]
builder = "dockerfile"

[build.envs]
NIXPACKS_NODE_PACKAGE_MANAGER = "npm"
NPM_CONFIG_PACKAGE_MANAGER = "npm"
DISABLE_BUN = "true"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
NIXPACKS_NODE_PACKAGE_MANAGER = "npm"
NPM_CONFIG_PACKAGE_MANAGER = "npm"
