[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"

[variables]
NIXPACKS_NODE_PACKAGE_MANAGER = "npm"
