// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azuqquiicdtmgkyeseub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6dXFxdWlpY2R0bWdreWVzZXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTU1NzEsImV4cCI6MjA2OTM3MTU3MX0.LAfi-6d-QBTJbxmHnxXF_NIu4jPvLRV2DkCpgAX_-CY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});